# Generated by Django 4.2.9 on 2024-02-20 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Memory_type',
                'verbose_name_plural': 'Memory_types',
            },
        ),
        migrations.CreateModel(
            name='ProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProcessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ProcessorModel',
                'verbose_name_plural': 'ProcessorModels',
            },
        ),
        migrations.CreateModel(
            name='Soket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Soket',
                'verbose_name_plural': 'Sokets',
            },
        ),
        migrations.CreateModel(
            name='VideocardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'VideocardBrand',
                'verbose_name_plural': 'VideocardBrands',
            },
        ),
        migrations.CreateModel(
            name='VideoChipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'VideoChipset',
                'verbose_name_plural': 'VideoChipsets',
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tdp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('raiting', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='archive.videocardbrand')),
                ('videochipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videochipset', to='archive.videochipset')),
            ],
            options={
                'verbose_name': 'VideoCard',
                'verbose_name_plural': 'VideoCards',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfs', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('raiting', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='archive.processorbrand')),
                ('memory_type', models.ManyToManyField(related_name='memory_type', to='archive.memory_type')),
                ('processor_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_model', to='archive.processormodel')),
                ('soket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soket', to='archive.soket')),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processors',
            },
        ),
    ]
