# Generated by Django 4.2.9 on 2024-09-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_components_processor_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components_processor',
            options={'verbose_name': 'ProcessorComponent', 'verbose_name_plural': 'ProcessorsComponents'},
        ),
        migrations.AlterModelOptions(
            name='components_ram',
            options={'verbose_name': 'Component_RAM', 'verbose_name_plural': 'Components_RAM'},
        ),
        migrations.AlterModelOptions(
            name='components_videocard',
            options={'verbose_name': 'Component_VideoCard', 'verbose_name_plural': 'Components_VideoCard'},
        ),
        migrations.RemoveField(
            model_name='components_processor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='components_videocard',
            name='category',
        ),
        migrations.DeleteModel(
            name='CardsComponents',
        ),
    ]
