# Generated by Django 4.2.9 on 2024-02-20 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tdp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('raiting_for_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Components_RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mfs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tdp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('raiting_for_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
    ]
