# Generated by Django 4.2.9 on 2024-04-06 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_componetns', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Components_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tdp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting_for_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdp', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Components_RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mfs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tdp', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Components_VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting_for_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdp', models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_videocard', to='components.components_videocard', verbose_name='component_videocard')),
            ],
        ),
    ]
