# Generated by Django 4.2.9 on 2024-02-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('archive', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components_videocard',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.AddField(
            model_name='components_videocard',
            name='videocard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_videocard', to='archive.videocard', verbose_name='videocard'),
        ),
        migrations.AddField(
            model_name='components_ram',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.AddField(
            model_name='components_ram',
            name='memory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.memory_type'),
        ),
        migrations.AddField(
            model_name='components_processor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.AddField(
            model_name='components_processor',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_processor', to='archive.processor', verbose_name='processor'),
        ),
        migrations.AddField(
            model_name='components_motherboard',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.AddField(
            model_name='components_motherboard',
            name='memory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.memory_type'),
        ),
        migrations.AddField(
            model_name='components_motherboard',
            name='soket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.soket'),
        ),
        migrations.AddField(
            model_name='components_memory',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
    ]
