# Generated by Django 4.2.9 on 2024-04-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components_processor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_processor', to='components.cardscomponents', verbose_name='component_processor'),
        ),
        migrations.AlterField(
            model_name='components_videocard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_videocard', to='components.cardscomponents', verbose_name='component_videocard'),
        ),
    ]
