# Generated by Django 4.2.9 on 2024-05-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_components_processor_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components_processor',
            options={'verbose_name': 'CardsComponent', 'verbose_name_plural': 'CardsComponents'},
        ),
        migrations.AlterModelOptions(
            name='components_ram',
            options={'verbose_name': 'Component_RAM', 'verbose_name_plural': 'Components_RAM'},
        ),
        migrations.AlterModelOptions(
            name='components_videocard',
            options={'verbose_name': 'Component_VideoCard', 'verbose_name_plural': 'Components_VideoCard'},
        ),
    ]
