# Generated by Django 4.2.9 on 2024-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_components_processor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='components_memory',
            name='category',
            field=models.CharField(default='Memory', max_length=20),
        ),
        migrations.AddField(
            model_name='components_memory',
            name='type_memory',
            field=models.CharField(choices=[('SSD', 'Ssd'), ('Sata', 'Sata')], default='DDR3', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components_motherboard',
            name='category',
            field=models.CharField(default='Motherboard', max_length=20),
        ),
        migrations.AddField(
            model_name='components_ram',
            name='category',
            field=models.CharField(default='RAM', max_length=20),
        ),
        migrations.AlterField(
            model_name='components_processor',
            name='category',
            field=models.CharField(default='Processor', max_length=20),
        ),
        migrations.AlterField(
            model_name='components_videocard',
            name='category',
            field=models.CharField(default='VideoCard', max_length=20),
        ),
        migrations.DeleteModel(
            name='CardsComponents',
        ),
    ]
