# Generated by Django 4.2.9 on 2024-04-06 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('power_supply', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('raiting', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components_memory', verbose_name='memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components_motherboard', verbose_name='motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components_processor', verbose_name='processor')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components_ram', verbose_name='ram')),
                ('videocart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components_videocard', verbose_name='videocart')),
            ],
        ),
    ]
