# Generated by Django 4.2.9 on 2024-05-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
